---
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/grzeshtoph/MicroServicesCourse-ConfigData.git
server:
  port: 8030
# For simplicity, disable security when posting to bus/refresh:  
management:
  security:
    enabled: false